### ISSUE TITLE
Crear el maquetado de dashboard

### ISSUE THREAD

**Issue by feranstirman1** [alvarogarcia1010/ayuda-un-peludo#14]

**Comment by feranstirman1** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Definir y maquetar dashboard](https://trello.com/c/O2WlpPs1/23-definir-y-maquetar-dashboard)

**Comment by alvarogarcia1010** [comment]
De plantilla 1: https://startbootstrap.com/template-overviews/sb-admin-2/ 
- [x]  Card para Usuarios registrados,
- [x] Card para usuarios administradores,
- [x] Card para publicaciones, 
- [x] Card de me empeluda
![captura de pantalla_2018-11-20_18-27-48](https://user-images.githubusercontent.com/34427195/48811226-6c6b1d00-ecf2-11e8-9cb0-5abbd2bd4227.png)

- [x]  Agregar Data Tables donde muestre los usuarios registrados
- Correlativo
- Nombre
- Apellido
- Username
- Columna que contenga un boton para hacer administrador.

![captura de pantalla_2018-11-20_18-37-22](https://user-images.githubusercontent.com/34427195/48811450-6cb7e800-ecf3-11e8-9506-f404494d3f45.png)

- Plugin Data Tables: https://datatables.net/
- Muestra en plantilla: https://blackrockdigital.github.io/startbootstrap-sb-admin-2/pages/tables.html
