### ISSUE TITLE
Crear pantalla de configuracion

### ISSUE THREAD

**Issue by alvarogarcia1010** [alvarogarcia1010/ayuda-un-peludo#15]
[Ejemplo utilizando Bootstrap](https://getbootstrap.com/docs/4.1/components/list-group/#javascript-behavior)
Basarse en el diseño de pantalla de configuracion de GitHub.
- [x] Colocar List-Item de Cuenta 
![captura de pantalla_2018-11-20_21-13-36](https://user-images.githubusercontent.com/34427195/48816790-2bcace00-ed09-11e8-80b5-db3527eb5d1d.png)

Ademas de cambiar contraseña, que se pueda cambiar el correo 
![captura de pantalla_2018-11-20_21-18-43](https://user-images.githubusercontent.com/34427195/48816962-e35fe000-ed09-11e8-9a18-1dde0877c779.png)

**Comment by feranstirman1** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [hacer pantalla de configuracion, basarse en github](https://trello.com/c/Ls8rjqw4/39-hacer-pantalla-de-configuracion-basarse-en-github)
