### ISSUE TITLE
Validacion de formularios

### ISSUE THREAD

**Issue by alvarogarcia1010** [alvarogarcia1010/ayuda-un-peludo#18]
Ocupando [Validaciones de Bootstrap](https://getbootstrap.com/docs/4.1/components/forms/#validation)
![captura de pantalla_2018-11-23_19-32-10](https://user-images.githubusercontent.com/34427195/48963370-80af5400-ef56-11e8-964f-2c684071f67c.png)

Y tomando como base lo que hizo @ryanes97  
![captura de pantalla_2018-11-23_19-33-31](https://user-images.githubusercontent.com/34427195/48963379-b2281f80-ef56-11e8-9a37-ee019d7f2316.png)

- [x] Definir Los mensajes apropiados al validar los campos (esos que aparecen en rojo y verde)
- [x] Validar del lado del FrontEnd que confirmar contraseña sea igual a contraseña (Busca como hacer)
- [x] En la username agregar una expresion regular que valide que el primer caracter sea @
- [x] Hacer lo mismo con el formulario de Login
- [x] En la pantalla de configuracion agregar las mismas validaciones
- [x] Validar que la contraseña tenga minimo 8 caracteres

Expresion regular que valida usuario: **expRe = /@([a-z0-9_]{1,15})/**

**Comment by feranstirman1** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Validar campos de red social](https://trello.com/c/0tGweIfk/27-validar-campos-de-red-social)
