### ISSUE TITLE
Crear Controlador de Publicaciones

### ISSUE THREAD

**Issue by alvarogarcia1010** [alvarogarcia1010/ayuda-un-peludo#19]
Nombre de Controlador: PostManager
Tomas como base [UserManager](https://github.com/alvarogarcia1010/ayuda-un-peludo/blob/master/src/Controllers/UserManager.js).

Metodos del controlador: 
- [ ] createPost 
- [ ] updatePost (recibe como parametro el id del post)
- [ ] deletePost (recibe como parametro el id del post)
- [ ] Nuevo me empeluda
- [ ] nuevo comentario
- [ ] count me empeluda
- [ ] count comentario
- [ ] get comentarios por publicacion
- [ ] getPosts
- [ ] getPost (recibe el id del post)
- [ ] hacer los dos ultimos metodos pero filtrarlos por id de usuario

Rutas:  basarse en main.js
Nombre de la ruta: post.js
En el app ocupar -> app.use('/post' , indexRouter.postManager)
/ -> Obtener todas las publicaciones -> Method: GET
/:id -> Obtener publicacion por id -> Method: GET
/create -> Method: POST
/update/:id -> Method: PUT
/delete/:id -> Method: DELETE

En la ruta de user.js crear 2 nuevas rutas:
:idUser/posts/ ->  Obtener publicaciones de un solo usuario -> Method: GET
:idUser/post/:idPost ->  Obtener publicaciones de un solo usuario -> Method: GET

**Comment by feranstirman1** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Crear controlador de publicaciones](https://trello.com/c/2PReA9w8/30-crear-controlador-de-publicaciones)
